#-------------------------------------------
#      Spring Properties
#-------------------------------------------
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
      jdbc:
        batch_size: 4
    properties:
      javax.persistence:
        schema-generation.database.action: none
  h2.console.enabled: true
  servlet:
    multipart:
      enabled: true    
      max-file-size: 2050MB
      maxRequestSize: 2050MB  
      resolve-lazily: true   
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
server.port: 8081
