#-------------------------------------------
#      Spring Properties
#-------------------------------------------
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        batch_size: 4
    properties:
      javax.persistence:
        schema-generation.database.action: none
  servlet:
    multipart:
      enabled: true    
      max-file-size: 2050MB
      maxRequestSize: 2050MB  
      resolve-lazily: true   
  datasource:
    url: jdbc:sap://localhost:39041/?databaseName=HXE&reconnect=true&statementCacheSize=512
    driverClassName: com.sap.db.jdbc.Driver
    username: SYSTEM
    password: A77d8C84bca1
objectstore:
  credentials:
    accessKeyId: AKIAWSCM7XP3LOMKCIBA
    bucket: hcp-79d7d7cf-494e-46ce-951a-b9330fb26d72
    secretAccessKey: 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

